<!--BOOK_INFORMATION-->
<img style="float: right; width: 100px" src="https://raw.github.com/pyomeca/design/master/logo/logo_cropped_doc.svg?sanitize=true">
<font size="+3">Effective computation in Biomechanics</font>

<font size="+2">Romain Martinez</font> <a href="https://github.com/romainmartinez"><img src="https://img.shields.io/badge/github-romainmartinez-green?logo=github&style=social" /></a>

<!--NAVIGATION-->
< [Python fundamentals](01.01-python-base.ipynb) | [Contents](index.ipynb) | [Biomechanical analysis with Pyomeca](01.03-intro-to-pyomeca.ipynb) >

# Scientific computing with Numpy

<img style="float: right; width: 300px" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg?sanitize=true">

[Numpy](https://numpy.org/) is probably the most fundamental package for scientific computing in Python.

It provides a highly efficient interface to create and interact with multidimensional arrays.

Nearly every other scientific package uses or integrates with NumPy in some way.

The performance-sensitive parts of NumPy are all written in the C language, so they are very fast.

## Numpy arrays

The fundamental object of NumPy is its `numpy.array`, an $n$-dimensional array that is also present in some form in array-oriented languages such as MATLAB.

In [1]:
import numpy as np  # we import numpy as "np" to avoid typing "numpy" each time

%load_ext lab_black

vector = np.array([10, 11, 12])

In [2]:
print(type(vector))

<class 'numpy.ndarray'>


In [3]:
vector.shape

(3,)

Let’s start things off by forming a 3-dimensional array with 36 consecutive numbers

In [4]:
matrix = np.arange(36).reshape(3, 4, 3)
matrix

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

Picturing high-dimensional arrays in two dimensions can be difficult.

One intuitive way to think about an array’s shape is to simply say:

> matrix is a 3 by 4 by 3 array

In [5]:
matrix.shape

(3, 4, 3)

In [6]:
print(f"{matrix.ndim=}")
print(f"{matrix.shape=}")
print(f"{matrix.size=}")
print(f"{matrix.dtype=}")

matrix.ndim=3
matrix.shape=(3, 4, 3)
matrix.size=36
matrix.dtype=dtype('int64')


Visually, `matrix` could be thought of as a container of three 4x3 grids (or a rectangular prism) and would look like this:

<img src="https://files.realpython.com/media/arr3d.7442cd4e11c6.jpg" width=700px>

Data with greater than two dimensions are tough to picture, but they are __everywhere__ in biomechanics, so better get used to it!

### Creating a 4x3 array

In [7]:
np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])  # from a list

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [8]:
np.arange(12).reshape(4, 3)  # with consecutive numbers

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [9]:
np.zeros((4, 3))  # with zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [10]:
np.ones((4, 3))  # with ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
np.empty((4, 3))  # with last value used

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.random.rand(4, 3)  # with random numbers

array([[0.60735616, 0.87319008, 0.9659621 ],
       [0.18343821, 0.95529461, 0.82921231],
       [0.04650347, 0.47699624, 0.95430011],
       [0.69373147, 0.70725343, 0.33456704]])

### Array indexing

More details in the [indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) section of the documentation.

#### Integer indexing

In [13]:
array = np.arange(12).reshape(4, 3)
array

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [14]:
# first row second column & second row third column
array[[0, 1], [1, 2]]

array([1, 5])

#### Slicing

In [15]:
# first two rows
array[:2, :]

array([[0, 1, 2],
       [3, 4, 5]])

In [16]:
# last row and columns 1 & 2
array[-1, 1:3]

array([10, 11])

**Warning**: a slice of an array is a view into the same data, so modifying it will **modify the original array**.

#### Boolean indexing

In [17]:
array > 5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
array[array > 5]

array([ 6,  7,  8,  9, 10, 11])

## Array math

More details in the [mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html) section of the official documentation.

In [19]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [20]:
x + y
# or np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [21]:
x - y
# or np.substract(x, y)

array([[-4, -4],
       [-4, -4]])

In [22]:
x * y
# or np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [23]:
x / y
# or np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [24]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

**Warning**: unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication.

We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

In [25]:
x @ y
# or np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [26]:
np.sum(x, axis=0)
# or x.sum(axis=0)

array([4, 6])

In [27]:
np.sum(x, axis=1)
# or x.sum(axis=1)

array([3, 7])

## Reshaping

In [28]:
x

array([[1, 2],
       [3, 4]])

In [29]:
x.T

array([[1, 3],
       [2, 4]])

In [30]:
x.reshape(-1)

array([1, 2, 3, 4])

## Your turn

Here are some EMG data from the anterior deltoid during a box lifting task:

In [31]:
import pandas as pd
import altair as alt

emg_dataframe = pd.read_csv("../data/emgs.csv").query('filename == "12kg_H2_3"')

base = alt.Chart(emg_dataframe)
line = base.mark_line().encode(x="index", y="delt_ant")
rule = base.mark_rule(color="firebrick", size=2).encode(y="mean(delt_ant)")

above_base = alt.Chart(emg_dataframe.query("delt_ant > delt_ant.mean()"))
points = above_base.mark_point(color="red").encode(x="index", y="delt_ant")
rect = above_base.mark_errorband(extent="stdev").encode(y="delt_ant")

line + points + rule + rect

alt.LayerChart(...)

In [32]:
emg = emg_dataframe["delt_ant"].values

From the `emg` Numpy array:
1. Selects only points that are above the average of the EMG signal (red points).
2. From these points, calculate how many points are within plus or minus one standard deviation of the mean (red points outside the blue area).

<!--NAVIGATION-->
< [Python fundamentals](01.01-python-base.ipynb) | [Contents](index.ipynb) | [Biomechanical analysis with Pyomeca](01.03-intro-to-pyomeca.ipynb) >