<!--BOOK_INFORMATION-->
<img style="float: right; width: 100px" src="https://raw.github.com/pyomeca/design/master/logo/logo_cropped.svg?sanitize=true">

# Effective computation in Biomechanics
## with [pyomeca](https://github.com/pyomeca/pyomeca)
Romain Martinez (martinez.staps@gmail.com | [GitHub](https://github.com/romainmartinez))

<!--NAVIGATION-->
< [Introduction to Python](01.01-Intro-to-Python.ipynb) | [Contents](Index.ipynb) | [Introduction to pyomeca](02.00-Intro-to-Pyomeca.ipynb) >

# Introduction to Numpy



<img style="float: right; width: 300px" src="https://upload.wikimedia.org/wikipedia/commons/1/1a/NumPy_logo.svg?sanitize=true">

[Numpy](http://www.numpy.org/) is the core library for scientific computing in Python.

If you are already familiar with _MATLAB_, you might find [this tutorial](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html) useful.

## Array

In [1]:
import numpy as np

### Vector array

In [2]:
# vector array
a = np.array([10, 11, 12])

print(type(a))
print(a.shape)
print(a)

a[2] = 22
print(a)

<class 'numpy.ndarray'>
(3,)
[10 11 12]
[10 11 22]


### Matrix array

In [3]:
b = np.array([[10, 11, 12], [1, 2, 3]])
print(b.shape)
print(b)
print(b[0, 1])

(2, 3)
[[10 11 12]
 [ 1  2  3]]
11


### Array indexing

More details in the [indexing](https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html) section of the documentation.

In [4]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
# another way of creating the same array will be `np.arange(1, 13).reshape(3, 4)`

print(a.shape)
a

(3, 4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#### Integer indexing

In [5]:
# first row second column & second row third column 
a[[0, 1], [1, 2]]

array([2, 7])

#### Slicing

In [6]:
# first two rows
a[:2, :]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
# last row and columns 1 & 2
a[-1, 1:3]

array([10, 11])

**Warning**: a slice of an array is a view into the same data, so modifying it will **modify the original array**.

#### Boolean indexing

In [8]:
[a > 5]

[array([[False, False, False, False],
        [False,  True,  True,  True],
        [ True,  True,  True,  True]])]

In [9]:
a[a>5]

array([ 6,  7,  8,  9, 10, 11, 12])

## Array math

More details in the [mathematical functions](https://docs.scipy.org/doc/numpy/reference/routines.math.html) section of the official documentation.

In [10]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

In [11]:
x + y
# or np.add(x, y)

array([[ 6,  8],
       [10, 12]])

In [12]:
x - y
# or np.substract(x, y)

array([[-4, -4],
       [-4, -4]])

In [13]:
x * y
# or np.multiply(x, y)

array([[ 5, 12],
       [21, 32]])

In [14]:
x / y
# or np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [15]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

**Warning**: unlike MATLAB, `*` is elementwise multiplication, not matrix multiplication.

We instead use the dot function to compute inner products of vectors, to multiply a vector by a matrix, and to multiply matrices.

In [16]:
x.dot(y)
# or np.dot(x, y)

array([[19, 22],
       [43, 50]])

In [17]:
np.sum(x, axis=0)

array([4, 6])

In [18]:
np.sum(x, axis=1)

array([3, 7])

## Reshaping

In [19]:
x 

array([[1, 2],
       [3, 4]])

In [20]:
x.T

array([[1, 3],
       [2, 4]])

In [21]:
x.reshape(-1)

array([1, 2, 3, 4])

## Reading and writing MATLAB files

The [scipy](https://www.scipy.org/) package includes the functions to read (`scipy.io.loadmat`) and write (`scipy.io.savemat`) MATLAB files.

<!--NAVIGATION-->
< [Introduction to Python](01.01-Intro-to-Python.ipynb) | [Contents](Index.ipynb) | [Introduction to pyomeca](02.00-Intro-to-Pyomeca.ipynb) >